### PR TITLE
Add price to staked balance and reward value

### PR DESCRIPTION
**Pull request by avargaz**
Adds value of current balance and next reward.
Screen Shot 2021-11-25 at 9 56 16 AM

### CODE REVIEW

**Comment by skolli853780** [comment]
Very good idea

**Comment by seankwarren** [comment]
I think this is left out intentionally. Its misleading and can have negative impacts on volatility.

**Comment by avargas-remind** [comment]
Agree. Also noticed this is not the official repo. It is the old version

**Comment by skolli853780** [comment]
can you please give me link for official rep

**Comment by avargaz** [comment]
It must be private because they do a lot of changes to the page. And this repo has almost no commits.
I think this repo points to this URL: https://legacy.wonderland.money/

**Pull request closed without merging**
